language: android
android:
  components:
    - build-tools-25.0.2
    - android-25

notifications:
  email: false

before_install:

  # for gradle output style
  - export TERM=dumb

  # move to app directory and make gradle executable
  - cd app/calendar-widget
  - chmod +x gradlew

  # environment info
  - ./gradlew -v
  - uname -a

# Let's build...
script: ./gradlew clean build